spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://dpg-d3fn6bp5pdvs73be510g-a.oregon-postgres.render.com:5432/roth?sslmode=require
    username: roth_user
    password: ArTLhsNDeUNVYbabV93WNrQI0Og5rZUL
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false

file:
  upload-dir: ./uploads

logging:
  level:
    com.setec: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE

server:
  port: 8080
